version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-optional.txt
    - requirements: requirements-document.txt
    - method: pip
      path: .

sphinx:
  configuration: doc/source/conf.py
