name: Run Tests and Upload Coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
          pip install pytest pytest-cov

      - name: Download test .db
        run: |
          wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
          unzip chinook.zip
          mv chinook.db ./test/unit/sqlp

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=neuralib --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ytsimon2004/neuralib
        continue-on-error: true
