name: Run Tests and Upload Coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment with uv
        run: uv venv .venv

      - name: Install dependencies
        run: uv pip install -e .[dev]

      - name: Download test .db
        run: |
          wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
          unzip chinook.zip
          mv chinook.db ./test/unit/sqlp

      - name: Run tests and generate coverage report
        run: pytest --cov=neuralib --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ytsimon2004/neuralib
        continue-on-error: true
