name: Release and Publish Python Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # For PyPI trusted publishing

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          python-version: "3.10"

      - name: Build wheels/sdist with uv
        run: uv build --no-sources

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels_neuralib
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release

    permissions:
      id-token: write  # Required for Trusted Publishing

    steps:
      - name: Set up uv
        uses: astral-sh/setup-uv@v6.3.1

      - name: Download built wheels/sdist
        uses: actions/download-artifact@v4
        with:
          pattern: wheels_neuralib
          path: dist/
          merge-multiple: true

      - name: Remove unsupported wheels (optional)
        run: rm -f dist/*riscv*

      - name: Publish to PyPI
        run: uv publish -v dist/*
