name: Python Unittest

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]


    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtualenv with uv
        run: uv venv .venv

      - name: Install project and dev dependencies
        run: uv pip install -e .[dev]

      - name: Download test .db
        run: |
          wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
          unzip chinook.zip
          mv chinook.db ./test/unit/sqlp

      - name: Run unit tests
        env:
          PYTHONPATH: test
        run: |
          pytest test/unit -v

